name: Milestone changelog generator

on:
  workflow_call:
    inputs:
      milestone:
        required: true
        type: string
      repo-owner:
        required: true
        type: string
      repo-name:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  generate-milestone-changelog:
    runs-on: ubuntu-latest
    env:
      ci-tools-workdir: ${{ github.workspace }}/ci-tools
    steps:
      #----------------------------------------------
      #      check out to actual workspace repo
      #----------------------------------------------
      # - name: Checkout
      #   uses: actions/checkout@v3
      #----------------------------------------------
      #      check out to ci tools repo
      #----------------------------------------------
      - name: Checkout CI Tools repo
        uses: actions/checkout@v3
        with:
          repository: ynput/ci-tools
          ref: main
          path: ./ci-tools
      #----------------------------------------------
      #      set-up python
      #----------------------------------------------
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Test CI Tools work dir content
        run: |
          cd "${{ env.ci-tools-workdir }}"
          ls -l
      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
            virtualenvs-create: true
            virtualenvs-in-project: true
            installer-parallel: true
      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Install dependencies
        run: poetry --directory=${{ env.ci-tools-workdir }} install --no-interaction
      #----------------------------------------------
      #              run changelog generator
      #----------------------------------------------
      - name: Run changelog generator
        id: changelog
        run : |
          delimiter=$(openssl rand -hex 8)
          {
              echo "OUT<<$delimiter"
              sed -e '$a\' $(python ${{ env.ci-tools-workdir }}/scripts/changelog.py get-milestone-changelog --milestone ${{ inputs.milestone }})
              echo "$delimiter"
          } >> "$GITHUB_OUTPUT"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
          GITHUB_REPOSITORY_OWNER: ${{ inputs.repo-owner }}
          GITHUB_REPOSITORY_NAME: ${{ inputs.repo-name }}
      - name: Test print the change log result
        run: echo "${{ steps.changelog.outputs.OUT }}"