name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options:
        - monalisa
        - cschleiden
      message:
        required: true
      use-emoji:
        type: boolean
        description: Include  emojis
      test:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Set variable switch
      id: secretToken
      with:
        cond: ${{ github.event.inputs.test != '' }}
        if_true: ${{ github.event.inputs.name }}  # string value
        if_false: ${{ github.event.inputs.message }} # string value
    - name: Send greeting
      run: |
        echo "${{ github.event.inputs.message }} ${{ fromJSON('[":)", ":("]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"
        echo "${{ steps.secretToken.outputs.value }}"